.segment "ZEROPAGE": zeropage
.exportzp _x16_ram_bank, _x16_rom_bank

_x16_ram_bank = ram_bank
_x16_rom_bank = rom_bank

.org $00
ram_bank: .res 1
rom_bank: .res 1



.segment "IO": absolute

.export _VERA_ADDRx_L, _VERA_ADDRx_M, _VERA_ADDRx_H
.export _VERA_DATA0, _VERA_DATA1, _VERA_CTRL
.export _VERA_IEN, _VERA_ISR, _VERA_IRQLINE_L, _VERA_SCANLINE_L

.export _VERA_DC0_HSCALE, _VERA_DC0_VIDEO, _VERA_DC0_VSCALE, _VERA_DC0_BORDER
.export _VERA_DC1_HSTART, _VERA_DC1_HSTOP, _VERA_DC1_VSTART, _VERA_DC1_VSTOP
.export _VERA_DC2_FX_CTRL, _VERA_DC2_FX_TILEBASE, _VERA_DC2_FX_MAPBASE, _VERA_DC2_FX_MULT
.export _VERA_DC3_FX_X_INCR_L, _VERA_DC3_FX_X_INCR_H, _VERA_DC3_FX_Y_INCR_L, _VERA_DC3_FX_Y_INCR_H
.export _VERA_DC4_FX_X_POS_L, _VERA_DC4_FX_X_POS_H, _VERA_DC4_FX_Y_POS_L, _VERA_DC4_FX_Y_POS_H
.export _VERA_DC5_FX_X_POS_S, _VERA_DC5_FX_Y_POS_S, _VERA_DC5_FX_POLY_FILL_L, _VERA_DC5_FX_POLY_FILL_H
.export _VERA_DC6_FX_CACHE_L, _VERA_DC6_FX_CACHE_M, _VERA_DC6_FX_CACHE_H, _VERA_DC6_FX_CACHE_U, _VERA_DC6_FX_ACCUM_RESET, _VERA_DC6_FX_ACCUM
.export _VERA_DC63_VER0, _VERA_DC63_VER1, _VERA_DC63_VER2, _VERA_DC63_VER3

.export _VERA_L0_CFG, _VERA_L0_MAPBASE, _VERA_L0_TILEBASE, _VERA_L0_BITMAPBASE
.export _VERA_L0_HSCROLL_L, _VERA_L0_HSCROLL_H, _VERA_L0_VSCROLL_L, _VERA_L0_VSCROLL_H
.export _VERA_L1_CFG, _VERA_L1_MAPBASE, _VERA_L1_TILEBASE, _VERA_L1_BITMAPBASE
.export _VERA_L1_HSCROLL_L, _VERA_L1_HSCROLL_H, _VERA_L1_VSCROLL_L, _VERA_L1_VSCROLL_H

.export _VERA_AUDIO_CTRL, _VERA_AUDIO_RATE, _VERA_AUDIO_DATA, _VERA_SPI_DATA, _VERA_SPI_CTRL

_VERA_ADDRx_L       = VERA_ADDRx_L
_VERA_ADDRx_M       = VERA_ADDRx_M
_VERA_ADDRx_H       = VERA_ADDRx_H
_VERA_DATA0         = VERA_DATA0
_VERA_DATA1         = VERA_DATA1
_VERA_CTRL          = VERA_CTRL
_VERA_IEN           = VERA_IEN
_VERA_ISR           = VERA_ISR
_VERA_IRQLINE_L     = VERA_IRQ_SCAN
_VERA_SCANLINE_L    = VERA_IRQ_SCAN

_VERA_DC0_HSCALE    = VERA_DC_R1
_VERA_DC0_VIDEO     = VERA_DC_R0
_VERA_DC0_VSCALE    = VERA_DC_R2
_VERA_DC0_BORDER    = VERA_DC_R3
_VERA_DC1_HSTART    = VERA_DC_R0
_VERA_DC1_HSTOP     = VERA_DC_R1
_VERA_DC1_VSTART    = VERA_DC_R2
_VERA_DC1_VSTOP     = VERA_DC_R3

_VERA_DC2_FX_CTRL       = VERA_DC_R0
_VERA_DC2_FX_TILEBASE   = VERA_DC_R1
_VERA_DC2_FX_MAPBASE    = VERA_DC_R2
_VERA_DC2_FX_MULT       = VERA_DC_R3
_VERA_DC3_FX_X_INCR_L   = VERA_DC_R0
_VERA_DC3_FX_X_INCR_H   = VERA_DC_R1
_VERA_DC3_FX_Y_INCR_L   = VERA_DC_R2
_VERA_DC3_FX_Y_INCR_H   = VERA_DC_R3
_VERA_DC4_FX_X_POS_L    = VERA_DC_R0
_VERA_DC4_FX_X_POS_H    = VERA_DC_R1
_VERA_DC4_FX_Y_POS_L    = VERA_DC_R2
_VERA_DC4_FX_Y_POS_H    = VERA_DC_R3
_VERA_DC5_FX_X_POS_S        = VERA_DC_R0
_VERA_DC5_FX_Y_POS_S        = VERA_DC_R1
_VERA_DC5_FX_POLY_FILL_L    = VERA_DC_R2
_VERA_DC5_FX_POLY_FILL_H    = VERA_DC_R3

_VERA_DC6_FX_CACHE_L    = VERA_DC_R0
_VERA_DC6_FX_CACHE_M    = VERA_DC_R1
_VERA_DC6_FX_CACHE_H    = VERA_DC_R2
_VERA_DC6_FX_CACHE_U    = VERA_DC_R3
_VERA_DC6_FX_ACCUM_RESET= VERA_DC_R0
_VERA_DC6_FX_ACCUM      = VERA_DC_R1

_VERA_DC63_VER0 = VERA_DC_R0
_VERA_DC63_VER1 = VERA_DC_R1
_VERA_DC63_VER2 = VERA_DC_R2
_VERA_DC63_VER3 = VERA_DC_R3

_VERA_L0_CFG        = VERA_L0_CFG
_VERA_L0_MAPBASE    = VERA_L0_MAPBASE
_VERA_L0_TILEBASE   = VERA_L0_TILEBASE
_VERA_L0_BITMAPBASE = VERA_L0_TILEBASE
_VERA_L0_HSCROLL_L  = VERA_L0_HSCROLL_L
_VERA_L0_HSCROLL_H  = VERA_L0_HSCROLL_H
_VERA_L0_VSCROLL_L  = VERA_L0_VSCROLL_L
_VERA_L0_VSCROLL_H  = VERA_L0_VSCROLL_H
_VERA_L1_CFG        = VERA_L1_CFG
_VERA_L1_MAPBASE    = VERA_L1_MAPBASE
_VERA_L1_TILEBASE   = VERA_L1_TILEBASE
_VERA_L1_BITMAPBASE = VERA_L1_TILEBASE
_VERA_L1_HSCROLL_L  = VERA_L1_HSCROLL_L
_VERA_L1_HSCROLL_H  = VERA_L1_HSCROLL_H
_VERA_L1_VSCROLL_L  = VERA_L1_VSCROLL_L
_VERA_L1_VSCROLL_H  = VERA_L1_VSCROLL_H

_VERA_AUDIO_CTRL    = VERA_AUDIO_CTRL
_VERA_AUDIO_RATE    = VERA_AUDIO_RATE
_VERA_AUDIO_DATA    = VERA_AUDIO_DATA
_VERA_SPI_DATA      = VERA_SPI_DATA
_VERA_SPI_CTRL      = VERA_SPI_CTRL 

.org $9F20
VERA_ADDRx_L:       .res 1
VERA_ADDRx_M:       .res 1
VERA_ADDRx_H:       .res 1
VERA_DATA0:         .res 1
VERA_DATA1:         .res 1
VERA_CTRL:          .res 1
VERA_IEN:           .res 1
VERA_ISR:           .res 1
VERA_IRQ_SCAN:      .res 1

VERA_DC_R0:         .res 1
VERA_DC_R1:         .res 1
VERA_DC_R2:         .res 1
VERA_DC_R3:         .res 1

VERA_L0_CFG:        .res 1
VERA_L0_MAPBASE:    .res 1
VERA_L0_TILEBASE:   .res 1
VERA_L0_HSCROLL_L:  .res 1
VERA_L0_HSCROLL_H:  .res 1
VERA_L0_VSCROLL_L:  .res 1
VERA_L0_VSCROLL_H:  .res 1
VERA_L1_CFG:        .res 1
VERA_L1_MAPBASE:    .res 1
VERA_L1_TILEBASE:   .res 1
VERA_L1_HSCROLL_L:  .res 1
VERA_L1_HSCROLL_H:  .res 1
VERA_L1_VSCROLL_L:  .res 1
VERA_L1_VSCROLL_H:  .res 1

VERA_AUDIO_CTRL:    .res 1
VERA_AUDIO_RATE:    .res 1
VERA_AUDIO_DATA:    .res 1
VERA_SPI_DATA:      .res 1
VERA_SPI_CTRL:      .res 1

.export VERA_ADDR_INC_0, VERA_ADDR_INC_1, VERA_ADDR_INC_2, VERA_ADDR_INC_4
.export VERA_ADDR_INC_8, VERA_ADDR_INC_16, VERA_ADDR_INC_32, VERA_ADDR_INC_64
.export VERA_ADDR_INC_128, VERA_ADDR_INC_256, VERA_ADDR_INC_512
.export VERA_ADDR_INC_40, VERA_ADDR_INC_80, VERA_ADDR_INC_160
.export VERA_ADDR_INC_320, VERA_ADDR_INC_640
VERA_ADDR_INC_0 = (0 << 4)
VERA_ADDR_INC_1 = (1 << 4)
VERA_ADDR_INC_2 = (2 << 4)
VERA_ADDR_INC_4 = (3 << 4)
VERA_ADDR_INC_8 = (4 << 4)
VERA_ADDR_INC_16 = (5 << 4)
VERA_ADDR_INC_32 = (6 << 4)
VERA_ADDR_INC_64 = (7 << 4)
VERA_ADDR_INC_128 = (8 << 4)
VERA_ADDR_INC_256 = (9 << 4)
VERA_ADDR_INC_512 = (10 << 4)
VERA_ADDR_INC_40 = (11 << 4)
VERA_ADDR_INC_80 = (12 << 4)
VERA_ADDR_INC_160 = (13 << 4)
VERA_ADDR_INC_320 = (14 << 4)
VERA_ADDR_INC_640 = (15 << 4)



.segment "CODE": absolute
.export HIGH_RAM_START
HIGH_RAM_START = $A000